# Generated by Django 4.2.6 on 2023-10-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_joining_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='userid',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
