# Generated by Django 4.2.7 on 2023-11-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_remove_organisationregistrationrequest_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
