# Generated by Django 4.2.7 on 2023-12-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0008_alter_organisation_password_delete_organisationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='name',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
    ]
