# Generated by Django 4.2.7 on 2023-12-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0010_alter_organisation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='is_active',
        ),
    ]
