# Generated by Django 4.2.7 on 2023-12-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0012_alter_organisation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
