# Generated by Django 4.2.6 on 2023-10-24 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclepooling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelisting',
            name='seats_available',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
