# Generated by Django 4.2.7 on 2023-12-20 08:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_phone_number'),
        ('vehiclepooling', '0005_alter_vehiclelisting_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclelisting',
            name='eta',
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 20, 14, 27, 23, 608661)),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 20, 14, 27, 23, 608661)),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 20, 14, 27, 23, 608661)),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 20, 14, 27, 23, 608661)),
        ),
    ]
