# Generated by Django 4.2.7 on 2023-12-20 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclepooling', '0008_alter_vehiclelisting_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelisting',
            name='end_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='end_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='start_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
