# Generated by Django 4.2.7 on 2023-12-20 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_phone_number'),
        ('vehiclepooling', '0009_alter_vehiclelisting_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelisting',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_seats', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='vehiclepooling.vehiclelisting')),
            ],
        ),
    ]
