# Generated by Django 4.2.7 on 2024-01-02 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='joining_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2024)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='passout_year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2028)]),
        ),
    ]
