# Generated by Django 4.2.7 on 2023-12-03 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_adminuser_date_joined_remove_adminuser_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
