# Generated by Django 4.2.6 on 2023-10-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclepooling', '0003_alter_vehiclelisting_vehicle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelisting',
            name='vehicle_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
