# Generated by Django 4.2.6 on 2023-11-29 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_userid_alter_customuser_username'),
        ('vehiclepooling', '0004_vehiclelisting_vehicle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelisting',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
        ),
    ]
