# Generated by Django 4.2.6 on 2023-11-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_organisationregistrationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
