# Generated by Django 4.2.7 on 2023-11-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_alter_organisation_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationregistrationrequest',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
