# Generated by Django 4.2.7 on 2023-12-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_alter_organisation_password_organisationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='OrganisationToken',
        ),
    ]
