# Generated by Django 4.2.7 on 2023-12-02 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0009_remove_organisation_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={},
        ),
        migrations.AlterModelManagers(
            name='organisation',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='password',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='username',
        ),
        migrations.AddField(
            model_name='organisation',
            name='user',
            field=models.OneToOneField(default=13, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
