# Generated by Django 4.2.7 on 2023-12-19 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0011_remove_organisation_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='organisation_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
