# Generated by Django 4.2.7 on 2023-12-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0013_alter_organisation_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
