# Generated by Django 4.2.6 on 2023-11-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrecommendation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images/'),
        ),
    ]
