# Generated by Django 4.2.6 on 2023-11-15 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodrecommendation', '0012_alter_restaurant_number_of_recommendations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='number_of_recommendations',
        ),
    ]
