# Generated by Django 4.2.7 on 2023-12-03 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='is_staff',
        ),
    ]
