# Generated by Django 4.2.6 on 2023-11-07 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('overall_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('overall_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurant_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('service_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('ambience_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('top_recommendation', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('avg_user_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('avg_user_price_per_head', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodrecommendation.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
