# Generated by Django 4.2.7 on 2023-12-02 09:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_remove_customuser_branch_remove_customuser_division_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(default=20, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('joining_year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2023)])),
                ('passout_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2027)])),
                ('branch', models.CharField(choices=[('CSBS', 'CSBS'), ('AI&DS', 'AI&DS'), ('IT', 'IT'), ('ME', 'ME'), ('CE', 'CE'), ('CSE', 'CSE'), ('EEE', 'EEE'), ('ECE', 'ECE'), ('AEI', 'AEI')], max_length=10)),
                ('division', models.CharField(choices=[('N/A', 'N/A'), ('Alpha', 'Alpha'), ('Beta', 'Beta'), ('Gamma', 'Gamma')], max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
            ],
        ),
    ]
